export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT_CURRENT_USER = 'LOG_OUT_CURRENT_USER';
export const SET_USERS_LOADING_STATE = 'SET_USERS_LOADING_STATE';
export const SET_USER_ERROR = 'SET_USER_ERROR';
