export const SET_COMMUNITIES = 'SET_COMMUNITIES';
export const SET_COMMUNITIES_LOADING_STATE = 'SET_COMMUNITIES_LOADING_STATE';
export const SET_COMMUNITIES_ERROR = 'SET_COMMUNITIES_ERROR';

export const SET_COMMUNITY = 'SET_COMMUNITY';
export const SET_COMMUNITY_LOADING_STATE = 'SET_COMMUNITY_LOADING_STATE';
export const SET_COMMUNITY_ERROR = 'SET_COMMUNITY_ERROR';

export const ADD_MEMBER = 'ADD_MEMBER';
